### ISSUE TITLE
Launch Issue - OMP: Error #15

### ISSUE THREAD

**Issue by poglicouk** [t41372/Open-LLM-VTuber#3]
Running with MemGPT as my backend, however when attempting to launch, i'm running into the following error:
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.

Have you run into this previously?
Do you recommend using the KMP_DUPLICATE_LIB_OK=TRUE workaround?

**Comment by t41372** [comment]
I haven't run into a similar issue before. I have no idea. Is the error in MemGPT or this project?
If it is a MemGPT problem, try installing MemGPT in docker or a separate conda environment to avoid dependency conflicts between MemGPT and this project.
This issue seems to happen when `OpenMP` is loaded more than once. Not sure why. It is probably caused by some package used in this project, but I don't know which of them is the cause. If the error occurs in this project, maybe you can give me a bit more information, like the trace stack?

**Comment by poglicouk** [comment]
Thanks for the advice :) running memGPT in docker resolved it. Much appreciated!
